[window]
dimensions = {columns = 70, lines = 25}
position = { x = 50, y = 110}
padding = { x = 30, y = 30}
decorations = "None"
opacity = 1
blur = true
startup_mode = "Windowed"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 9

[colors]
cursor = { text = "#14ff6e", cursor = "#ffffff" }
[colors.primary]
foreground = "#328073"
dim_foreground = "#2d2d2e"
background = "#111111"

[bell]
animation = "EaseOutSine"
duration = 1

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 1000




